services:
  prometheus:
    image: prom/prometheus:v2.40.7
    ports:
      - 9090:9090
    volumes:
      - ./prom_config:/etc/prometheus
      - ./prom_data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  
  node-exporter:
    image: prom/node-exporter:v1.5.0
    ports:
      - 9100:9100

networks:
  default:
    name: prom_net
