global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564' # non-existent target in the network to demonstrate alert management

  - job_name: node_exporter
    static_configs:
      - targets:
        - 'node-exporter:9100'

  - job_name: test_counter
    static_configs:
      - targets:
        - 'counter:8002'

  - job_name: test_gauge
    static_configs:
      - targets:
        - 'gauge:8003'

  - job_name: test_histogram
    static_configs:
      - targets:
        - 'histogram:8004'

  - job_name: test_summary
    static_configs:
      - targets:
        - 'summary:8005'
